In [1]:
from miran import *
from matplotlib import pyplot as p

In [4]:
f = folderfiles('/Users/angel/Insync/Datasets/RS200/trevor/', recursive=False)

In [43]:
f = folderfiles('/Users/angel/Desktop/Temperley_Diatonic/', recursive=False)
data = []
for item in f:
    with open(item, 'r') as my_file:
        tonic, mode = my_file.read().split()
        data.append((item, tonic, mode))
dtre = pd.DataFrame(data, columns=('path', 'tonic', 'mode'))

In [44]:
df_to_excel(dtre, '/Users/angel/Desktop/Temper.xlsl')


Saving evaluation results to /Users/angel/Desktop/Temper.xlsl


In [16]:
def find_mode_flat(mode_array):

    modes = {'ionian':     np.array([1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.]),
             'dorian':     np.array([1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0.]),
             'phrygian':   np.array([1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.]),
             'lydian':     np.array([1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1.]),
             'mixolydian': np.array([1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0.]),
             'aeolian':    np.array([1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0.]),
             'harmonic':   np.array([1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1.]),
             'locrian':    np.array([1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0.]),
             'pentamaj':   np.array([1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.]),
             'pentamin':   np.array([1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0.])}

    rank = []
    for mode in modes.keys():
        dis = distance(modes[mode], mode_array, dist='cityblock')
        rank.append((dis,mode))
    rank.sort(key=lambda tup: tup[0])
    return rank

In [7]:
for item in f:
    a = pd.read_csv(item, sep='\t', names=('onset','bar','chord', 'root relative', 'scale degree', 'key','root pc'))
    a['key'].replace('', np.nan, inplace=True)
    a = a.dropna(subset=['key'], how='all')
    n_keys = len(a.key.value_counts())
    if n_keys > 1:
        print(item)
        print(a.key.value_counts())
        print(a.key)
        print('\n')
    
    if n_keys == 1:
        profile = np.zeros(12)
        for chord in a.chord: 
            pcs = roman_to_pcs(chord)
            for pc in pcs:
                profile[pc] = 1
        modo = find_mode_flat(profile)
        if modo[0][0] == 0:
            print(item)
            print(a.key[1])
            print(profile)
            print(modo)
            annotation = '{}\t{}'.format( pc_to_chroma(a.key[1]), modo[0][1])
            print(annotation)
            print('\n')
            make_annotation_file(item, annotation, output_dir='/Users/angel/Desktop/Trevor_Diatonic/')
            

/Users/angel/Insync/Datasets/RS200/trevor/fake_plastic_trees_tdc.clt
9.0
[ 1.  0.  1.  0.  1.  1.  0.  1.  0.  1.  0.  1.]
[(0.0, 'ionian'), (2.0, 'pentamaj'), (2.0, 'mixolydian'), (2.0, 'lydian'), (4.0, 'dorian'), (4.0, 'harmonic'), (6.0, 'pentamin'), (6.0, 'aeolian'), (8.0, 'phrygian'), (10.0, 'locrian')]
A	ionian


Creating estimation file for '/Users/angel/Insync/Datasets/RS200/trevor/fake_plastic_trees_tdc.clt' in '/Users/angel/Desktop/Trevor_Diatonic/'
/Users/angel/Insync/Datasets/RS200/trevor/i_still_havent_found_what_im_looking_for_tdc.clt
1.0
[ 1.  0.  1.  0.  1.  1.  0.  1.  0.  1.  0.  1.]
[(0.0, 'ionian'), (2.0, 'pentamaj'), (2.0, 'mixolydian'), (2.0, 'lydian'), (4.0, 'dorian'), (4.0, 'harmonic'), (6.0, 'pentamin'), (6.0, 'aeolian'), (8.0, 'phrygian'), (10.0, 'locrian')]
C#	ionian


Creating estimation file for '/Users/angel/Insync/Datasets/RS200/trevor/i_still_havent_found_what_im_looking_for_tdc.clt' in '/Users/angel/Desktop/Trevor_Diatonic/'
/Users/angel/Insync/Datasets/

/Users/angel/Insync/Datasets/RS200/trevor/both_sides_now_tdc.clt
6.0
[ 1.  0.  1.  0.  1.  1.  0.  1.  0.  1.  0.  1.]
[(0.0, 'ionian'), (2.0, 'pentamaj'), (2.0, 'mixolydian'), (2.0, 'lydian'), (4.0, 'dorian'), (4.0, 'harmonic'), (6.0, 'pentamin'), (6.0, 'aeolian'), (8.0, 'phrygian'), (10.0, 'locrian')]
F#	ionian


Creating estimation file for '/Users/angel/Insync/Datasets/RS200/trevor/both_sides_now_tdc.clt' in '/Users/angel/Desktop/Trevor_Diatonic/'
/Users/angel/Insync/Datasets/RS200/trevor/with_or_without_you_tdc.clt
2.0
[ 1.  0.  1.  0.  1.  1.  0.  1.  0.  1.  0.  1.]
[(0.0, 'ionian'), (2.0, 'pentamaj'), (2.0, 'mixolydian'), (2.0, 'lydian'), (4.0, 'dorian'), (4.0, 'harmonic'), (6.0, 'pentamin'), (6.0, 'aeolian'), (8.0, 'phrygian'), (10.0, 'locrian')]
D	ionian


Creating estimation file for '/Users/angel/Insync/Datasets/RS200/trevor/with_or_without_you_tdc.clt' in '/Users/angel/Desktop/Trevor_Diatonic/'
/Users/angel/Insync/Datasets/RS200/trevor/rave_on_tdc.clt
7.0
[ 1.  0.  1.  0. 

/Users/angel/Insync/Datasets/RS200/trevor/folsom_prison_blues_tdc.clt
5.0
[ 1.  0.  1.  0.  1.  1.  0.  1.  0.  1.  0.  1.]
[(0.0, 'ionian'), (2.0, 'pentamaj'), (2.0, 'mixolydian'), (2.0, 'lydian'), (4.0, 'dorian'), (4.0, 'harmonic'), (6.0, 'pentamin'), (6.0, 'aeolian'), (8.0, 'phrygian'), (10.0, 'locrian')]
F	ionian


Creating estimation file for '/Users/angel/Insync/Datasets/RS200/trevor/folsom_prison_blues_tdc.clt' in '/Users/angel/Desktop/Trevor_Diatonic/'
/Users/angel/Insync/Datasets/RS200/trevor/redemption_song_tdc.clt
7.0
[ 1.  0.  1.  0.  1.  1.  0.  1.  0.  1.  0.  1.]
[(0.0, 'ionian'), (2.0, 'pentamaj'), (2.0, 'mixolydian'), (2.0, 'lydian'), (4.0, 'dorian'), (4.0, 'harmonic'), (6.0, 'pentamin'), (6.0, 'aeolian'), (8.0, 'phrygian'), (10.0, 'locrian')]
G	ionian


Creating estimation file for '/Users/angel/Insync/Datasets/RS200/trevor/redemption_song_tdc.clt' in '/Users/angel/Desktop/Trevor_Diatonic/'
/Users/angel/Insync/Datasets/RS200/trevor/heroes_tdc.clt
2.0
[ 1.  0.  1.  0. 

In [6]:
profile

array([ 1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.])

In [ ]:
m = np.array([1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1.])

In [ ]:
def find_mode_flat(mode_array):

    modes = {'ionian':     np.array([1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.]),
             'dorian':     np.array([1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0.]),
             'phrygian':   np.array([1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.]),
             'lydian':     np.array([1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1.]),
             'mixolydian': np.array([1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0.]),
             'aeolian':    np.array([1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0.]),
             'locrian':    np.array([1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0.])}

    rank = []
    for mode in modes.keys():
        dis = crosscorrelation(modes[mode], mode_array)
        rank.append((dis,mode))
    rank.sort(key=lambda tup: tup[0], reverse=True)
    print(rank)
    return rank[0][1]


In [ ]:
a['key'].replace('', np.nan, inplace=True)